spring:
  datasource:
    url: jdbc:sqlite:./sjf.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  flyway:
    locations: classpath:migration/flyway
    clean-on-validation-error: true