sql:
  dialect: SQLITE

spring:
  datasource:
    url: jdbc:sqlite:./sjf.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  # only for development (on production must be commented)
  flyway:
    clean-on-validation-error: true
    clean-disabled: false